### ISSUE TITLE
Broken Links

### ISSUE THREAD

**Issue by RitwikSingh28** [HackSlashNITP/LibraLink#1]
## Description
Broken link in `Contribution Guidelines` in `Further Resources` section of `README.md`.

### Tasks:
* Provide correct link to HackSlash's `CONTRIBUTIONS.md` in `hackslash-contrib` repository
* Remove `Issue Tracker` in `Further Resources` Section

@HackSlashNITP/team-nougat-flutter 
Those who wish to resolve this issue, kindly mention your willingness in the comment section.

**Comment by ShubhamTiwari55** [comment]
Sorry for being late @RitwikSingh28. Kindly assign this issue to me
