### ISSUE TITLE
Launcher icon not suitable in light mode

### ISSUE THREAD

**Issue by ShubhamTiwari55** [HackSlashNITP/LibraLink#10]
@RitwikSingh28 sir the launcher icon is not visible properly in light mode. As I was using dark mode in my android device, I couldn't see it. Kindly assign this issue to me so that I can add a background to the logo and then update it as launcher icon. 
![WhatsApp Image 2023-10-28 at 17 43 55_4d84a91e](https://github.com/HackSlashNITP/LibraLink/assets/125534462/d8fdd760-bf54-4a50-923e-bc30b4b9f54f)

**Comment by RitwikSingh28** [comment]
Assigned to you. You may start working on it now
