### ISSUE TITLE
Overflow in the sign in page

### ISSUE THREAD

**Issue by piyuuussh** [HackSlashNITP/LibraLink#24]
There's a bottom overflow in the signin page.
![238a700b-e613-4888-91ef-a0411ad4567a](https://github.com/HackSlashNITP/LibraLink/assets/130576546/0f078a6a-e057-4036-b461-fa5b4e435940)

**Comment by divyansh12git** [comment]
@piyuuussh I want to resolve this issue please assign me

**Comment by piyuuussh** [comment]
Okay @divyansh12git  I'm assigning you this issue make sure to resolve before tomorrow midnight

**Comment by divyansh12git** [comment]
@piyuuussh  @ShubhamTiwari55 
Resolved the issue and along with enhanced the code and ui.
Created the pull request.
@everyone please review it
![Screenshot_2023-11-12-02-20-32-44_ac789816193d8a58aa81475d15b7a225](https://github.com/HackSlashNITP/LibraLink/assets/123203281/488885d3-486c-45b6-b346-8afd59956e14)
