### ISSUE TITLE
UI enhancement of signup page 

### ISSUE THREAD

**Issue by ShubhamTiwari55** [HackSlashNITP/LibraLink#26]
There is an issue with the UI part of signup page. Make the UI as per the design file with keeping an eye on widget sizes, font size and weight and make it fit for all screen sizes.
![image](https://github.com/HackSlashNITP/LibraLink/assets/125534462/dab7f7b4-8008-4019-8216-3f79abdad060)

**Comment by dev04sa** [comment]
@ShubhamTiwari55 assign this issue to me , I want to work on it

**Comment by ShubhamTiwari55** [comment]
@dev04sa Assigned it to you.
Deadline - today 8pm
