### ISSUE TITLE
UI enhancement of issued book page and removal of hard coded values 

### ISSUE THREAD

**Issue by ShubhamTiwari55** [HackSlashNITP/LibraLink#28]
The UI is not looking good; adjust height, width, font size and font weight according to the design file and replace the hard coded values of deadline, book name, author, issued and return date with dynamic values.
![image](https://github.com/HackSlashNITP/LibraLink/assets/125534462/17f5424f-9c02-4b06-a5b0-8866059ff9c1)

**Comment by shradhaj06** [comment]
I will do this!
 @ShubhamTiwari55

**Comment by piyuuussh** [comment]
Okay @shradhaj06 you have been assigned this issue.
deadline - 17 midnight

**Comment by ShubhamTiwari55** [comment]
Closing this issue as it has been resolved
