### ISSUE TITLE
Issue in build gradle

### ISSUE THREAD

**Issue by piyuuussh** [HackSlashNITP/LibraLink#37]
The build gradle in both code had errors due to firebase integration

<img width="725" alt="image" src="https://github.com/HackSlashNITP/LibraLink/assets/130576546/65bf9cc2-502e-40fd-9ad9-435b6d8245f2">

**Comment by Yashrajdps13** [comment]
Assign me this issue

**Comment by piyuuussh** [comment]
This issue is assigned to you
