### ISSUE TITLE
Replace Default App Icon with LibraLink Logo

### ISSUE THREAD

**Issue by RitwikSingh28** [HackSlashNITP/LibraLink#6]
If interested on working on this issue, kindly ask to be assigned...

**Comment by ShubhamTiwari55** [comment]
@RitwikSingh28 I am interested to resolve this issue. Kindly assign this issue to me.

**Comment by RitwikSingh28** [comment]
@ShubhamTiwari55 
You have been assigned this issue. Kindly get it done before 22:00 IST

**Comment by ShubhamTiwari55** [comment]
@RitwikSingh28 Sir this issue has been resolved. Kindly review the changes
