### ISSUE TITLE
Maintain the state( auth state ) of the app

### ISSUE THREAD

**Issue by piyuuussh** [HackSlashNITP/LibraLink#61]
To maintain the state of the app means that once the app is logged in, then even if you close the app and again open it, it'll stay as logged in. And you don't need to enter the Id and password again and again.

**Comment by Yashrajdps13** [comment]
Assign me

**Comment by piyuuussh** [comment]
Assigning the issue #61 to @Yashrajdps13  and your deadline is 9th jan
