### ISSUE TITLE
Login with the username as well

### ISSUE THREAD

**Issue by piyuuussh** [HackSlashNITP/LibraLink#62]
As of now one can login the app only using the email and password. But it should be compatible to get login using username as well

**Comment by Yashrajdps13** [comment]
Assign me

**Comment by piyuuussh** [comment]
Assigning the issue to @Yashrajdps13 get it resolved by 9th jan.

**Comment by piyuuussh** [comment]
This issue is being closed as of now we don't have any method to to login through username...
